### ISSUE TITLE
Add API to stream Missions/Boosters

### ISSUE THREAD

**Issue by kameshsampath** [fabric8-launch/booster-catalog#115]
Once the index is triggered the application get's a Future handle, it will be worth adding a Booster Stream API - which can be used by consumers to start fetching data from stream

**Comment by quintesse** [comment]
@kameshsampath what is this API you refer to exactly? It isn't immediately clear to me what you are referring to?

**Comment by gastaldi** [comment]
Can you elaborate more? What's wrong with `BoosterCatalog.getBoosters().stream()`♧?

**Comment by quintesse** [comment]
Perhaps you are referring to using web sockets like we do for the status updates? Or perhaps something react-like?

**Comment by kameshsampath** [comment]
sorry moving to fabric8-launch/booster-catalog-service

**Comment by gastaldi** [comment]
This issue was moved to fabric8-launch/booster-catalog-service#12
